<p>Introduction into <b>TensorFlow</b></p>

In [28]:
import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy, SparseCategoricalCrossentropy
from tensorflow.keras.models import Sequential
import matplotlib.pyplot as plt
from tensorflow.keras.activations import sigmoid, relu, softmax, linear
from tensorflow.keras.callbacks import LambdaCallback
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler

In [27]:
path = "/home/sam/Documents/projects/machine_learning/data/houses.txt"
with open(path, "r") as file:
    data = pd.read_csv(file)
    
print(data)


    9.520000000000000000e+02  2.000000000000000000e+00  \
0                     1244.0                       3.0   
1                     1947.0                       3.0   
2                     1725.0                       3.0   
3                     1959.0                       3.0   
4                     1314.0                       2.0   
..                       ...                       ...   
94                    1224.0                       2.0   
95                    1432.0                       2.0   
96                    1660.0                       3.0   
97                    1212.0                       3.0   
98                    1050.0                       2.0   

    1.000000000000000000e+00  6.500000000000000000e+01  \
0                        1.0                      64.0   
1                        2.0                      17.0   
2                        2.0                      42.0   
3                        2.0                      15.0   
4            

In [4]:
print(data.columns)

Index(['9.520000000000000000e+02', '2.000000000000000000e+00',
       '1.000000000000000000e+00', '6.500000000000000000e+01',
       '2.715000000000000000e+02'],
      dtype='object')


In [19]:
X = np.array(data[['9.520000000000000000e+02', '2.000000000000000000e+00',
       '1.000000000000000000e+00', '6.500000000000000000e+01']])
Y = np.array(data["2.715000000000000000e+02"]).reshape((99, 1))

In [20]:
print(Y.shape)
print(X.shape)

(99, 1)
(99, 4)


<p>Build a neural network model with four layers</p>

In [30]:
def print_cost(epoch, logs):
    if epoch % 100 == 0:
        print("Epoch {}: Cost: {:.4f}".format(epoch, logs["loss"]))
        

model = Sequential([
    Dense(units=4, activation="relu"),
    Dense(units=5, activation="relu"),
    Dense(units=5, activation="relu"),
    Dense(units=1, activation="linear")
])

model.compile(optimizer=Adam(learning_rate=1e-2), loss=MeanSquaredError())

print_cost_callback = LambdaCallback(on_epoch_end=print_cost)

model.fit(X, Y, epochs=3000, verbose=0, callbacks=[print_cost_callback])


Epoch 0: Cost: 3626.8940
Epoch 100: Cost: 2605.3904
Epoch 200: Cost: 2626.6438
Epoch 300: Cost: 2748.0403
Epoch 400: Cost: 2376.2268
Epoch 500: Cost: 2403.6284
Epoch 600: Cost: 2340.4973
Epoch 700: Cost: 2174.8076
Epoch 800: Cost: 1912.2559
Epoch 900: Cost: 2345.8140
Epoch 1000: Cost: 1940.4100
Epoch 1100: Cost: 1507.0641
Epoch 1200: Cost: 1176.0742
Epoch 1300: Cost: 1007.7576
Epoch 1400: Cost: 1043.3967
Epoch 1500: Cost: 874.2327
Epoch 1600: Cost: 599.6199
Epoch 1700: Cost: 873.8104
Epoch 1800: Cost: 547.1035
Epoch 1900: Cost: 616.5281
Epoch 2000: Cost: 603.5197
Epoch 2100: Cost: 846.7098
Epoch 2200: Cost: 536.2705
Epoch 2300: Cost: 678.7761
Epoch 2400: Cost: 484.9008
Epoch 2500: Cost: 1056.4470
Epoch 2600: Cost: 486.8701
Epoch 2700: Cost: 458.7963
Epoch 2800: Cost: 2600.2944
Epoch 2900: Cost: 657.7026


In [32]:
params = model.get_weights()
print(params)

[array([[ 1.12645626e-01, -6.88382268e-01, -8.38078380e-01,
        -7.70414830e-04],
       [-8.30423260e+00,  2.01053441e-01, -1.85999870e-01,
         7.03159761e+00],
       [-1.71599674e+01, -4.48221147e-01, -4.01478350e-01,
         1.73080082e+01],
       [-5.43166220e-01,  7.76636779e-01, -8.25375319e-02,
         1.33946821e-01]], dtype=float32), array([ 15.575144,   0.      ,   0.      , -16.769892], dtype=float32), array([[-0.03980999,  0.6210434 , -0.32219124, -0.6721661 ,  0.27146584],
       [-0.2347359 , -0.39472064, -0.24097091,  0.20652926,  0.37573755],
       [-0.6017963 ,  0.14220089, -0.5884743 , -0.24713409, -0.33864886],
       [-0.21960114, -0.42095712, -0.5388693 ,  0.161758  , -0.5414823 ]],
      dtype=float32), array([ 0.29420346, 16.437983  ,  4.973587  ,  0.        , -0.3360558 ],
      dtype=float32), array([[-0.18034689, -0.7392713 ,  0.40601483, -0.0547213 , -0.5557957 ],
       [ 0.9740198 , -0.44784158,  0.6580812 , -0.3298852 ,  1.0859977 ],
       [

In [33]:
summ = model.summary()
print(summ)

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 4)                 20        
                                                                 
 dense_25 (Dense)            (None, 5)                 25        
                                                                 
 dense_26 (Dense)            (None, 5)                 30        
                                                                 
 dense_27 (Dense)            (None, 1)                 6         
                                                                 
Total params: 81 (324.00 Byte)
Trainable params: 81 (324.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [40]:
path1 = "/home/sam/Documents/projects/machine_learning/data/dog_data1.csv"
with open(path1, "r") as file:
    data1 = pd.read_csv(file)
print(data1)

      Unnamed: 0     height     weight  bark_days  ear_head_ratio  breed
0           2836  39.697810  31.740980        9.0        0.193120      2
1           1002  36.710641  21.140427       26.0        0.163527      0
2           1075  34.726930  19.817954       24.0        0.386113      0
3           1583  32.324884  30.812210       18.0        0.463242      1
4            248  37.691499  21.794333       28.0        0.118190      0
...          ...        ...        ...        ...             ...    ...
3445        1571  25.816115  14.540287        9.0        0.205467      1
3446         914  35.196253  20.130835       24.0        0.323976      0
3447         146  35.417276  20.278184       25.0        0.295218      0
3448        3156  37.132770  29.542374        7.0        0.141267      2
3449        2198  33.294319  33.235797       19.0        0.485071      1

[3450 rows x 6 columns]


In [41]:
print(data1.columns)

Index(['Unnamed: 0', 'height', 'weight', 'bark_days', 'ear_head_ratio',
       'breed'],
      dtype='object')


In [42]:
X = np.array(data1[['height', 'weight', 'bark_days', 'ear_head_ratio']])
Y = np.array(data1["breed"]).reshape((3450, 1))

norm = MinMaxScaler()
X = norm.fit_transform(X)

print(X.shape)
print(Y.shape)

(3450, 4)
(3450, 1)


In [53]:
X_train = X[:2800, :]
X_val = X[2800:3000, :]
X_test = X[3000: , :]
Y_train = Y[:2800]
Y_val = Y[2800:3000]
Y_test = Y[3000:]

print(X_train.shape)
print(X_val.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_val.shape)
print(Y_test.shape)

(2800, 4)
(200, 4)
(450, 4)
(2800, 1)
(200, 1)
(450, 1)


In [44]:
print(data1["breed"].unique())

[2 0 1]


In [45]:
def print_cost(epoch, logs):
    if epoch % 10 == 0:
        print("Epoch {}: Cost: {:.4f}".format(epoch, logs["loss"]))
        
        
model1 = Sequential([
    Dense(units=4, activation="relu"),
    Dense(units=6, activation="relu"),
    Dense(units=6, activation="relu"),
    Dense(units=3, activation="relu"),
    Dense(units=2, activation="relu"),
    Dense(units=3, activation="softmax") 
])

model1.compile(optimizer=Adam(learning_rate=0.001),
               loss=SparseCategoricalCrossentropy())

print_cost_callback = LambdaCallback(on_epoch_end=print_cost)

model1.fit(X_train, Y_train, epochs=200, verbose=0, callbacks=[print_cost_callback])

Epoch 0: Cost: 0.9296
Epoch 10: Cost: 0.3359
Epoch 20: Cost: 0.1768
Epoch 30: Cost: 0.1078
Epoch 40: Cost: 0.0695
Epoch 50: Cost: 0.0174
Epoch 60: Cost: 0.0082
Epoch 70: Cost: 0.0047
Epoch 80: Cost: 0.0029
Epoch 90: Cost: 0.0018
Epoch 100: Cost: 0.0012
Epoch 110: Cost: 0.0008
Epoch 120: Cost: 0.0005
Epoch 130: Cost: 0.0004
Epoch 140: Cost: 0.0002
Epoch 150: Cost: 0.0002
Epoch 160: Cost: 0.0001
Epoch 170: Cost: 0.0001
Epoch 180: Cost: 0.0001
Epoch 190: Cost: 0.0000


In [46]:
p_val = model1.predict(X_val)
p_train = model1.predict(X_train)
print(p_val[:20])

88/88 [==============================] - 0s 2ms/step
[[1.0000000e+00 1.3213920e-09 0.0000000e+00]
 [1.0000000e+00 1.5789501e-08 0.0000000e+00]
 [1.0000000e+00 2.0887061e-09 0.0000000e+00]
 [1.0000000e+00 1.2524537e-09 0.0000000e+00]
 [1.2694323e-10 1.0000000e+00 1.9653876e-23]
 [1.0000000e+00 2.0518103e-09 0.0000000e+00]
 [5.9186156e-08 1.0000000e+00 8.6126829e-16]
 [1.0000000e+00 2.0501920e-08 0.0000000e+00]
 [5.9575662e-08 1.0000000e+00 1.2289798e-15]
 [2.6735233e-10 1.0000000e+00 1.2656000e-22]
 [1.0000000e+00 1.4307944e-09 0.0000000e+00]
 [1.0000000e+00 8.1172313e-10 0.0000000e+00]
 [3.7915041e-05 4.9984756e-05 9.9991214e-01]
 [2.6250527e-08 1.0000000e+00 7.5503504e-17]
 [3.7915041e-05 4.9984756e-05 9.9991214e-01]
 [3.7915041e-05 4.9984756e-05 9.9991214e-01]
 [1.0461318e-07 9.9999988e-01 8.3684263e-15]
 [1.0000000e+00 9.8834141e-10 0.0000000e+00]
 [1.0000000e+00 8.6393346e-09 0.0000000e+00]
 [1.0000000e+00 1.2698786e-09 0.0000000e+00]]


In [47]:
c_val = np.argmax(p_val, axis=1)
c_train = np.argmax(p_train, axis=1)

print(c_val)

[0 0 0 0 1 0 1 0 1 1 0 0 2 1 2 2 1 0 0 0 0 0 0 0 2 0 0 2 0 2 1 2 0 2 0 1 1
 1 2 0 1 1 2 1 1 0 1 0 1 1 1 0 2 0 0 1 2 0 1 2 1 2 1 1 2 1 0 2 0 1 0 0 2 2
 0 2 0 1 2 2 1 0 0 0 1 2 1 2 0 2 2 1 0 0 2 0 1 1 0 0 2 0 0 0 1 1 0 1 0 2 0
 1 2 1 1 1 1 1 2 0 0 1 2 1 0 0 1 1 1 1 0 0 0 1 0 1 0 2 1 1 1 1 0 0 1 1 2 2
 1 1 1 1 0 0 1 0 2 2 2 1 0 1 1 2 0 1 2 0 2 1 1 0 0 1 1 0 1 1 2 0 2 0 1 1 0
 2 0 0 0 0 0 1 1 0 0 2 0 1 0 2]


In [56]:
Y_val = Y_val.reshape((1, 200)).flatten()
Y_train = Y_train.reshape((1, 2800)).flatten()


In [57]:
accuracy = np.sum([1 if i==j else 0 for i,j in zip(c_val, Y_val)])/len(c_val)
accuracy1 = np.sum([1 if i==j else 0 for i,j in zip(c_train, Y_train)])/len(c_train)
print(accuracy)
print(accuracy1)

1.0
1.0


In [58]:
Y_test = Y_test.reshape((1, 450)).flatten()
p_test = model1.predict(X_test)
c_test = np.argmax(p_test, axis=1)
accuracy2 = np.sum([1 if i==j else 0 for i,j in zip(c_test, Y_test)])/len(c_test)
print(accuracy2)

15/15 [==============================] - 0s 2ms/step
1.0
